export const fakeRoute = {
  citys: [43, 44, 42, 41, 40],
  createdAt: new Date(),
  description: "description",
  id: "891ebef9-552b-433b-8fc5-bb4280905053",
  major_goods: [""],
  title: "title",
  updatedAt: new Date(),
  user_id: "uid",
  country: "오스만",
  region: "카리브해",
  endMonth: "3",
  startMonth: "6",
}

export const fakeRoutes = [{
  citys: [0, 1],
  createdAt: new Date(),
  description: "description",
  id: "1",
  major_goods: [""],
  title: "title1",
  updatedAt: new Date(),
  user_id: "uid",
  country: "오스만",
  region: "카리브해",
  endMonth: "3",
  startMonth: "6",
}, {
  citys: [0, 1],
  createdAt: new Date(),
  description: "description",
  id: "2",
  major_goods: [""],
  title: "title2",
  updatedAt: new Date(),
  user_id: "uid",
  country: "오스만",
  region: "동지중해",
  endMonth: "2",
  startMonth: "6",
}]
